### ISSUE TITLE
bigtextbox.com is down!

### ISSUE THREAD

**Issue by johnnymugs** [nertzy/bigtextbox.com#1]
Expected behavior: when I visit bigtextbox.com I get a nice useful textbox to dump my thoughts into or signal to a co-worker that I'll BRB.
Actual behavior: when I visit bigtextbox.com I get a DNS error!

Hey Grant, hope you're doing well these days! Are you dropping bigtextbox.com? I'd be happy to take it over...

**Comment by johnnymugs** [comment]
It's back! Thanks Grant. Hope you're well...

**Comment by nertzy** [comment]
Somebody emailed me and then I fixed it!

Also, I am pairing with Masha today and she says hello!
